title: Adventures in Deep Space
email: adventuresindeepspace@gmail.com
description: Challenging observing projects for amateur astronomers of all ages
url: https://www.adventuresindeepspace.com
baseurl: /adventures.github.io
markdown: kramdown

theme: minima
plugins:
  - jekyll-latex

kramdown:
  parse_block_html: true
